version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///./echoguard.db
    depends_on:
      - redis
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    command: npm start

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  celery:
    build: ./backend
    volumes:
      - ./backend:/app
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=sqlite:///./echoguard.db
    depends_on:
      - redis
    command: celery -A src.celery_app worker --loglevel=info

volumes:
  redis_data: